export interface FlagSummary {
  key: string;
  name?: string;
  description?: string | null;
  kind: 'boolean' | 'string' | 'number' | 'json';
  variations: Array<{ id: string; value: unknown; name?: string }>;
  archivedAt?: string | null;
  temporary?: boolean;
  environments?: Record<string, { lastEvaluatedAt: string | null; stale?: boolean }>;
}

function quote(key: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
}

export function typeOf(value: unknown, indent = '  '): string {
  if (value === null) return 'null';
  if (Array.isArray(value)) {
    const items = Array.from(new Set(value.map((v) => typeOf(v, indent))));
    return items.length === 0
      ? 'unknown[]'
      : items.length === 1
        ? `${items[0]}[]`
        : `Array<${items.join(' | ')}>`;
  }
  switch (typeof value) {
    case 'string':
      return 'string';
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'object': {
      const entries = Object.entries(value as Record<string, unknown>);
      if (entries.length === 0) return 'Record<string, unknown>';
      return `{ ${entries.map(([k, v]) => `${quote(k)}: ${typeOf(v, indent)}`).join('; ')} }`;
    }
    default:
      return 'unknown';
  }
}

export function flagType(flag: FlagSummary): string {
  if (flag.kind === 'boolean') return 'boolean';
  if (flag.kind === 'string') return 'string';
  if (flag.kind === 'number') return 'number';
  return Array.from(new Set(flag.variations.map((v) => typeOf(v.value)))).join(' | ') || 'unknown';
}

export function generateTypes(
  project: string,
  flags: FlagSummary[],
  generatedAt = new Date().toISOString(),
): string {
  const active = flags.filter((f) => !f.archivedAt).sort((a, b) => a.key.localeCompare(b.key));
  const lines = [
    `// Generated by @ashamrai/flags-cli for project "${project}" at ${generatedAt}. Do not edit.`,
    '',
    'export interface GeneratedFlagTypes {',
    ...active.map((f) => `  ${JSON.stringify(f.key)}: ${flagType(f)};`),
    '}',
    '',
    `export const FLAG_KEYS = [${active.map((f) => JSON.stringify(f.key)).join(', ')}] as const;`,
    '',
    'export type FlagKey = (typeof FLAG_KEYS)[number];',
    '',
    "declare module '@ashamrai/flags-node' {",
    '  interface FlagTypes extends GeneratedFlagTypes {}',
    '}',
    '',
    "declare module '@ashamrai/flags-web' {",
    '  interface WebFlagTypes extends GeneratedFlagTypes {}',
    '}',
    '',
  ];
  return lines.join('\n');
}
